SHELL:=/bin/bash

test:
	go test -covermode=count -coverprofile=./profile.coverprofile -parallel 5 -v ./...

verification:
	go vet ./...
	golangci-lint run --enable-all --disable=lll --disable=gocyclo --disable=dupl --disable=unparam --disable=gochecknoglobals --deadline=300s --tests=false ./...
	CGO_ENABLED=0 errcheck ./...
